---
- name: User creation using host scope variables
  hosts: 172.31.92.195
  tasks:
   - name: User creation
     user:
      name: "{{a}}"
      password: "{{b}}"
      uid: "{{c}}"
      home: "{{d}}"
      shell: "{{e}}"
...
