---
- name: Install multiple s/w applications
  hosts: all
  tasks:
   - name: Install s/w
     apt:
      name: ['tree', 'git', 'maven']
      state: ['present','absent','latest']
      update_cache: ['no','no','yes']
... 
